name: publish
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD
            image: dualwu/debuginfo-upload-server
          - registry: harbor.zelostech.com.cn:5443
            username: ZELOS_USERNAME
            password: ZELOS_PASSWORD
            image: harbor.zelostech.com.cn:5443/business/dualwu/debuginfo-upload-server
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=true
            prefix=
            suffix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    # add some test based on publish docker
